// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.81.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "lazysodium.d.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

class LazysodiumImpl implements Lazysodium {
  final LazysodiumPlatform _platform;
  factory LazysodiumImpl(ExternalLibrary dylib) =>
      LazysodiumImpl.raw(LazysodiumPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory LazysodiumImpl.wasm(FutureOr<WasmModule> module) =>
      LazysodiumImpl(module as ExternalLibrary);
  LazysodiumImpl.raw(this._platform);
  Future<KeyPair> genKeypair({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_gen_keypair(port_),
      parseSuccessData: (d) => _wire2api_key_pair(d),
      constMeta: kGenKeypairConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kGenKeypairConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "gen_keypair",
        argNames: [],
      );

  Future<String> bin2Hex({required Uint8List data, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(data);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bin2hex(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kBin2HexConstMeta,
      argValues: [data],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBin2HexConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bin2hex",
        argNames: ["data"],
      );

  Future<String> pkHexMethodKeyPair({required KeyPair that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_key_pair(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_pk_hex__method__KeyPair(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kPkHexMethodKeyPairConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kPkHexMethodKeyPairConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "pk_hex__method__KeyPair",
        argNames: ["that"],
      );

  Future<String> skHexMethodKeyPair({required KeyPair that, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_key_pair(that);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_sk_hex__method__KeyPair(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kSkHexMethodKeyPairConstMeta,
      argValues: [that],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kSkHexMethodKeyPairConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sk_hex__method__KeyPair",
        argNames: ["that"],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  KeyPair _wire2api_key_pair(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPair(
      bridge: this,
      pk: _wire2api_uint_8_list(arr[0]),
      sk: _wire2api_uint_8_list(arr[1]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: finalizer

class LazysodiumPlatform extends FlutterRustBridgeBase<LazysodiumWire> {
  LazysodiumPlatform(ffi.DynamicLibrary dylib) : super(LazysodiumWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_KeyPair> api2wire_box_autoadd_key_pair(KeyPair raw) {
    final ptr = inner.new_box_autoadd_key_pair_0();
    _api_fill_to_wire_key_pair(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_key_pair(
      KeyPair apiObj, ffi.Pointer<wire_KeyPair> wireObj) {
    _api_fill_to_wire_key_pair(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_key_pair(KeyPair apiObj, wire_KeyPair wireObj) {
    wireObj.pk = api2wire_uint_8_list(apiObj.pk);
    wireObj.sk = api2wire_uint_8_list(apiObj.sk);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class LazysodiumWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LazysodiumWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LazysodiumWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_gen_keypair(
    int port_,
  ) {
    return _wire_gen_keypair(
      port_,
    );
  }

  late final _wire_gen_keypairPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_gen_keypair');
  late final _wire_gen_keypair =
      _wire_gen_keypairPtr.asFunction<void Function(int)>();

  void wire_bin2hex(
    int port_,
    ffi.Pointer<wire_uint_8_list> data,
  ) {
    return _wire_bin2hex(
      port_,
      data,
    );
  }

  late final _wire_bin2hexPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_bin2hex');
  late final _wire_bin2hex = _wire_bin2hexPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_pk_hex__method__KeyPair(
    int port_,
    ffi.Pointer<wire_KeyPair> that,
  ) {
    return _wire_pk_hex__method__KeyPair(
      port_,
      that,
    );
  }

  late final _wire_pk_hex__method__KeyPairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_KeyPair>)>>('wire_pk_hex__method__KeyPair');
  late final _wire_pk_hex__method__KeyPair = _wire_pk_hex__method__KeyPairPtr
      .asFunction<void Function(int, ffi.Pointer<wire_KeyPair>)>();

  void wire_sk_hex__method__KeyPair(
    int port_,
    ffi.Pointer<wire_KeyPair> that,
  ) {
    return _wire_sk_hex__method__KeyPair(
      port_,
      that,
    );
  }

  late final _wire_sk_hex__method__KeyPairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_KeyPair>)>>('wire_sk_hex__method__KeyPair');
  late final _wire_sk_hex__method__KeyPair = _wire_sk_hex__method__KeyPairPtr
      .asFunction<void Function(int, ffi.Pointer<wire_KeyPair>)>();

  ffi.Pointer<wire_KeyPair> new_box_autoadd_key_pair_0() {
    return _new_box_autoadd_key_pair_0();
  }

  late final _new_box_autoadd_key_pair_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_KeyPair> Function()>>(
          'new_box_autoadd_key_pair_0');
  late final _new_box_autoadd_key_pair_0 = _new_box_autoadd_key_pair_0Ptr
      .asFunction<ffi.Pointer<wire_KeyPair> Function()>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>(
      'new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_KeyPair extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> pk;

  external ffi.Pointer<wire_uint_8_list> sk;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;
