// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.81.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import "lazysodium.d.dart";
import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

import 'dart:ffi' as ffi;

class LazysodiumImpl implements Lazysodium {
  final LazysodiumPlatform _platform;
  factory LazysodiumImpl(ExternalLibrary dylib) =>
      LazysodiumImpl.raw(LazysodiumPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory LazysodiumImpl.wasm(FutureOr<WasmModule> module) =>
      LazysodiumImpl(module as ExternalLibrary);
  LazysodiumImpl.raw(this._platform);
  Future<KeyPair> cryptoKxKeypair(
      {required int pkSize, required int skSize, dynamic hint}) {
    var arg0 = api2wire_usize(pkSize);
    var arg1 = api2wire_usize(skSize);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_crypto_kx_keypair(port_, arg0, arg1),
      parseSuccessData: _wire2api_key_pair,
      constMeta: kCryptoKxKeypairConstMeta,
      argValues: [pkSize, skSize],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoKxKeypairConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_kx_keypair",
        argNames: ["pkSize", "skSize"],
      );

  Future<Uint8List> cryptoBoxBeforenm(
      {required KeyPair keypair, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_key_pair(keypair);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_crypto_box_beforenm(port_, arg0),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kCryptoBoxBeforenmConstMeta,
      argValues: [keypair],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoBoxBeforenmConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_box_beforenm",
        argNames: ["keypair"],
      );

  Future<String> cryptoBoxBeforenmHex(
      {required KeyPair keypair, dynamic hint}) {
    var arg0 = _platform.api2wire_box_autoadd_key_pair(keypair);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) =>
          _platform.inner.wire_crypto_box_beforenm_hex(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kCryptoBoxBeforenmHexConstMeta,
      argValues: [keypair],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoBoxBeforenmHexConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_box_beforenm_hex",
        argNames: ["keypair"],
      );

  Future<SessionKey> cryptoKxClientSessionKeys(
      {required Uint8List clientPk,
      required Uint8List clientSk,
      required Uint8List serverPk,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(clientPk);
    var arg1 = _platform.api2wire_uint_8_list(clientSk);
    var arg2 = _platform.api2wire_uint_8_list(serverPk);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_crypto_kx_client_session_keys(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_session_key,
      constMeta: kCryptoKxClientSessionKeysConstMeta,
      argValues: [clientPk, clientSk, serverPk],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoKxClientSessionKeysConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_kx_client_session_keys",
        argNames: ["clientPk", "clientSk", "serverPk"],
      );

  Future<SessionKey> cryptoKxServerSessionKeys(
      {required Uint8List serverPk,
      required Uint8List serverSk,
      required Uint8List clientPk,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(serverPk);
    var arg1 = _platform.api2wire_uint_8_list(serverSk);
    var arg2 = _platform.api2wire_uint_8_list(clientPk);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_crypto_kx_server_session_keys(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_session_key,
      constMeta: kCryptoKxServerSessionKeysConstMeta,
      argValues: [serverPk, serverSk, clientPk],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoKxServerSessionKeysConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_kx_server_session_keys",
        argNames: ["serverPk", "serverSk", "clientPk"],
      );

  Future<Uint8List> cryptoStreamChacha20Xor(
      {required Uint8List message,
      required Uint8List nonce,
      required Uint8List key,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(message);
    var arg1 = _platform.api2wire_uint_8_list(nonce);
    var arg2 = _platform.api2wire_uint_8_list(key);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_crypto_stream_chacha20_xor(port_, arg0, arg1, arg2),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kCryptoStreamChacha20XorConstMeta,
      argValues: [message, nonce, key],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kCryptoStreamChacha20XorConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "crypto_stream_chacha20_xor",
        argNames: ["message", "nonce", "key"],
      );

  Future<Uint8List> cryptoAeadChacha20Poly1305Encrypt(
      {required Uint8List message,
      required Uint8List additionalData,
      required Uint8List nonce,
      required Uint8List key,
      dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(message);
    var arg1 = _platform.api2wire_uint_8_list(additionalData);
    var arg2 = _platform.api2wire_uint_8_list(nonce);
    var arg3 = _platform.api2wire_uint_8_list(key);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner
          .wire_crypto_aead_chacha20poly1305_encrypt(
              port_, arg0, arg1, arg2, arg3),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kCryptoAeadChacha20Poly1305EncryptConstMeta,
      argValues: [message, additionalData, nonce, key],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta
      get kCryptoAeadChacha20Poly1305EncryptConstMeta =>
          const FlutterRustBridgeTaskConstMeta(
            debugName: "crypto_aead_chacha20poly1305_encrypt",
            argNames: ["message", "additionalData", "nonce", "key"],
          );

  Future<String> binToHex({required Uint8List data, dynamic hint}) {
    var arg0 = _platform.api2wire_uint_8_list(data);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_bin_to_hex(port_, arg0),
      parseSuccessData: _wire2api_String,
      constMeta: kBinToHexConstMeta,
      argValues: [data],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kBinToHexConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "bin_to_hex",
        argNames: ["data"],
      );

  Future<Uint8List> hexToBin({required String hex, dynamic hint}) {
    var arg0 = _platform.api2wire_String(hex);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_hex_to_bin(port_, arg0),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kHexToBinConstMeta,
      argValues: [hex],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kHexToBinConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "hex_to_bin",
        argNames: ["hex"],
      );

  Future<Uint8List> randomBytesBuf({required int size, dynamic hint}) {
    var arg0 = api2wire_usize(size);
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_random_bytes_buf(port_, arg0),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kRandomBytesBufConstMeta,
      argValues: [size],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRandomBytesBufConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "random_bytes_buf",
        argNames: ["size"],
      );

  Future<Uint8List> randomNonceBytes({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_random_nonce_bytes(port_),
      parseSuccessData: _wire2api_uint_8_list,
      constMeta: kRandomNonceBytesConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRandomNonceBytesConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "random_nonce_bytes",
        argNames: [],
      );

  Future<String> randomNonceHex({dynamic hint}) {
    return _platform.executeNormal(FlutterRustBridgeTask(
      callFfi: (port_) => _platform.inner.wire_random_nonce_hex(port_),
      parseSuccessData: _wire2api_String,
      constMeta: kRandomNonceHexConstMeta,
      argValues: [],
      hint: hint,
    ));
  }

  FlutterRustBridgeTaskConstMeta get kRandomNonceHexConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "random_nonce_hex",
        argNames: [],
      );

  void dispose() {
    _platform.dispose();
  }
// Section: wire2api

  String _wire2api_String(dynamic raw) {
    return raw as String;
  }

  KeyPair _wire2api_key_pair(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyPair(
      pk: _wire2api_uint_8_list(arr[0]),
      sk: _wire2api_uint_8_list(arr[1]),
    );
  }

  SessionKey _wire2api_session_key(dynamic raw) {
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionKey(
      rx: _wire2api_uint_8_list(arr[0]),
      tx: _wire2api_uint_8_list(arr[1]),
    );
  }

  int _wire2api_u8(dynamic raw) {
    return raw as int;
  }

  Uint8List _wire2api_uint_8_list(dynamic raw) {
    return raw as Uint8List;
  }
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

@protected
int api2wire_usize(int raw) {
  return raw;
}
// Section: finalizer

class LazysodiumPlatform extends FlutterRustBridgeBase<LazysodiumWire> {
  LazysodiumPlatform(ffi.DynamicLibrary dylib) : super(LazysodiumWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_KeyPair> api2wire_box_autoadd_key_pair(KeyPair raw) {
    final ptr = inner.new_box_autoadd_key_pair_0();
    _api_fill_to_wire_key_pair(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_box_autoadd_key_pair(
      KeyPair apiObj, ffi.Pointer<wire_KeyPair> wireObj) {
    _api_fill_to_wire_key_pair(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_key_pair(KeyPair apiObj, wire_KeyPair wireObj) {
    wireObj.pk = api2wire_uint_8_list(apiObj.pk);
    wireObj.sk = api2wire_uint_8_list(apiObj.sk);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class LazysodiumWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LazysodiumWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LazysodiumWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>(
          'get_dart_object');
  late final _get_dart_object =
      _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          'drop_dart_object');
  late final _drop_dart_object =
      _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>(
          'new_dart_opaque');
  late final _new_dart_opaque =
      _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_crypto_kx_keypair(
    int port_,
    int pk_size,
    int sk_size,
  ) {
    return _wire_crypto_kx_keypair(
      port_,
      pk_size,
      sk_size,
    );
  }

  late final _wire_crypto_kx_keypairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.UintPtr, ffi.UintPtr)>>('wire_crypto_kx_keypair');
  late final _wire_crypto_kx_keypair =
      _wire_crypto_kx_keypairPtr.asFunction<void Function(int, int, int)>();

  void wire_crypto_box_beforenm(
    int port_,
    ffi.Pointer<wire_KeyPair> keypair,
  ) {
    return _wire_crypto_box_beforenm(
      port_,
      keypair,
    );
  }

  late final _wire_crypto_box_beforenmPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_KeyPair>)>>('wire_crypto_box_beforenm');
  late final _wire_crypto_box_beforenm = _wire_crypto_box_beforenmPtr
      .asFunction<void Function(int, ffi.Pointer<wire_KeyPair>)>();

  void wire_crypto_box_beforenm_hex(
    int port_,
    ffi.Pointer<wire_KeyPair> keypair,
  ) {
    return _wire_crypto_box_beforenm_hex(
      port_,
      keypair,
    );
  }

  late final _wire_crypto_box_beforenm_hexPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64,
              ffi.Pointer<wire_KeyPair>)>>('wire_crypto_box_beforenm_hex');
  late final _wire_crypto_box_beforenm_hex = _wire_crypto_box_beforenm_hexPtr
      .asFunction<void Function(int, ffi.Pointer<wire_KeyPair>)>();

  void wire_crypto_kx_client_session_keys(
    int port_,
    ffi.Pointer<wire_uint_8_list> client_pk,
    ffi.Pointer<wire_uint_8_list> client_sk,
    ffi.Pointer<wire_uint_8_list> server_pk,
  ) {
    return _wire_crypto_kx_client_session_keys(
      port_,
      client_pk,
      client_sk,
      server_pk,
    );
  }

  late final _wire_crypto_kx_client_session_keysPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_crypto_kx_client_session_keys');
  late final _wire_crypto_kx_client_session_keys =
      _wire_crypto_kx_client_session_keysPtr.asFunction<
          void Function(int, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_crypto_kx_server_session_keys(
    int port_,
    ffi.Pointer<wire_uint_8_list> server_pk,
    ffi.Pointer<wire_uint_8_list> server_sk,
    ffi.Pointer<wire_uint_8_list> client_pk,
  ) {
    return _wire_crypto_kx_server_session_keys(
      port_,
      server_pk,
      server_sk,
      client_pk,
    );
  }

  late final _wire_crypto_kx_server_session_keysPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_crypto_kx_server_session_keys');
  late final _wire_crypto_kx_server_session_keys =
      _wire_crypto_kx_server_session_keysPtr.asFunction<
          void Function(int, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_crypto_stream_chacha20_xor(
    int port_,
    ffi.Pointer<wire_uint_8_list> message,
    ffi.Pointer<wire_uint_8_list> nonce,
    ffi.Pointer<wire_uint_8_list> key,
  ) {
    return _wire_crypto_stream_chacha20_xor(
      port_,
      message,
      nonce,
      key,
    );
  }

  late final _wire_crypto_stream_chacha20_xorPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_crypto_stream_chacha20_xor');
  late final _wire_crypto_stream_chacha20_xor =
      _wire_crypto_stream_chacha20_xorPtr.asFunction<
          void Function(int, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  void wire_crypto_aead_chacha20poly1305_encrypt(
    int port_,
    ffi.Pointer<wire_uint_8_list> message,
    ffi.Pointer<wire_uint_8_list> additional_data,
    ffi.Pointer<wire_uint_8_list> nonce,
    ffi.Pointer<wire_uint_8_list> key,
  ) {
    return _wire_crypto_aead_chacha20poly1305_encrypt(
      port_,
      message,
      additional_data,
      nonce,
      key,
    );
  }

  late final _wire_crypto_aead_chacha20poly1305_encryptPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(
                  ffi.Int64,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>,
                  ffi.Pointer<wire_uint_8_list>)>>(
      'wire_crypto_aead_chacha20poly1305_encrypt');
  late final _wire_crypto_aead_chacha20poly1305_encrypt =
      _wire_crypto_aead_chacha20poly1305_encryptPtr.asFunction<
          void Function(
              int,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>();

  void wire_bin_to_hex(
    int port_,
    ffi.Pointer<wire_uint_8_list> data,
  ) {
    return _wire_bin_to_hex(
      port_,
      data,
    );
  }

  late final _wire_bin_to_hexPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_bin_to_hex');
  late final _wire_bin_to_hex = _wire_bin_to_hexPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_hex_to_bin(
    int port_,
    ffi.Pointer<wire_uint_8_list> hex,
  ) {
    return _wire_hex_to_bin(
      port_,
      hex,
    );
  }

  late final _wire_hex_to_binPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Int64, ffi.Pointer<wire_uint_8_list>)>>('wire_hex_to_bin');
  late final _wire_hex_to_bin = _wire_hex_to_binPtr
      .asFunction<void Function(int, ffi.Pointer<wire_uint_8_list>)>();

  void wire_random_bytes_buf(
    int port_,
    int size,
  ) {
    return _wire_random_bytes_buf(
      port_,
      size,
    );
  }

  late final _wire_random_bytes_bufPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'wire_random_bytes_buf');
  late final _wire_random_bytes_buf =
      _wire_random_bytes_bufPtr.asFunction<void Function(int, int)>();

  void wire_random_nonce_bytes(
    int port_,
  ) {
    return _wire_random_nonce_bytes(
      port_,
    );
  }

  late final _wire_random_nonce_bytesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_random_nonce_bytes');
  late final _wire_random_nonce_bytes =
      _wire_random_nonce_bytesPtr.asFunction<void Function(int)>();

  void wire_random_nonce_hex(
    int port_,
  ) {
    return _wire_random_nonce_hex(
      port_,
    );
  }

  late final _wire_random_nonce_hexPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_random_nonce_hex');
  late final _wire_random_nonce_hex =
      _wire_random_nonce_hexPtr.asFunction<void Function(int)>();

  ffi.Pointer<wire_KeyPair> new_box_autoadd_key_pair_0() {
    return _new_box_autoadd_key_pair_0();
  }

  late final _new_box_autoadd_key_pair_0Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_KeyPair> Function()>>(
          'new_box_autoadd_key_pair_0');
  late final _new_box_autoadd_key_pair_0 = _new_box_autoadd_key_pair_0Ptr
      .asFunction<ffi.Pointer<wire_KeyPair> Function()>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
          ffi
          .NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>(
      'new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>(
          'free_WireSyncReturn');
  late final _free_WireSyncReturn =
      _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

final class _Dart_Handle extends ffi.Opaque {}

final class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_KeyPair extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> pk;

  external ffi.Pointer<wire_uint_8_list> sk;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<
        ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message)>>;
typedef DartPort = ffi.Int64;

const int CRYPTO_NONCE_BYTES = 24;

const int CRYPTO_NONCE_HEX = 48;
