// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.81.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';

abstract class Lazysodium {
  Future<KeyPair> genKeypair({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGenKeypairConstMeta;

  Future<String> bin2Hex({required Uint8List data, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kBin2HexConstMeta;

  Future<String> pkHexMethodKeyPair({required KeyPair that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kPkHexMethodKeyPairConstMeta;

  Future<String> skHexMethodKeyPair({required KeyPair that, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSkHexMethodKeyPairConstMeta;
}

class KeyPair {
  final Lazysodium bridge;
  final Uint8List pk;
  final Uint8List sk;

  const KeyPair({
    required this.bridge,
    required this.pk,
    required this.sk,
  });

  Future<String> pkHex({dynamic hint}) => bridge.pkHexMethodKeyPair(
        that: this,
      );

  Future<String> skHex({dynamic hint}) => bridge.skHexMethodKeyPair(
        that: this,
      );
}
